CREATE TABLE public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client',
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);
-- Data for table `classification`
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
       ('Sport'),
       ('SUV'),
       ('Truck'),
       ('Sedan');

       INSERT INTO account (
    account_firstname,
    account_lastname,
    account_email,
    account_password,
    account_type
)
VALUES 
('Admin', 'User', 'admin@byui.edu', 'password123', 'Admin'),
('Test', 'User', 'test@byui.edu', 'testpassword', 'Client');

INSERT INTO inventory (
    inv_make,
    inv_model,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_year,
    classification_id
)
VALUES
('GM', 'Hummer', 'Huge interior with small interiors and powerful performance.', '/images/gm-hummer.jpg', '/images/gm-hummer-tn.jpg', 50000, 25000, 2018, 1),
('Jeep', 'Wrangler', 'Off-road capability with removable doors.', '/images/jeep-wrangler.jpg', '/images/jeep-wrangler-tn.jpg', 38000, 15000, 2019, 1),

('Ford', 'F150', 'Top selling truck with strong towing.', '/images/ford-f150.jpg', '/images/ford-f150-tn.jpg', 42000, 30000, 2020, 2),
('Chevrolet', 'Silverado', 'Reliable truck with great hauling.', '/images/chevy-silverado.jpg', '/images/chevy-silverado-tn.jpg', 45000, 20000, 2021, 2),

('Honda', 'Accord', 'Smooth sedan with great fuel efficiency.', '/images/honda-accord.jpg', '/images/honda-accord-tn.jpg', 30000, 10000, 2022, 3),
('Toyota', 'Camry', 'Comfortable sedan with advanced safety.', '/images/toyota-camry.jpg', '/images/toyota-camry-tn.jpg', 32000, 18000, 2020, 3),

('Porsche', '911', 'High-performance sport coupe.', '/images/porsche-911.jpg', '/images/porsche-911-tn.jpg', 120000, 5000, 2022, 4),
('Corvette', 'Stingray', 'Fast American sports car.', '/images/corvette-stingray.jpg', '/images/corvette-stingray-tn.jpg', 95000, 7000, 2021, 4),

('Dodge', 'Challenger', 'Customized muscle car.', '/images/dodge-challenger.jpg', '/images/dodge-challenger-tn.jpg', 60000, 12000, 2020, 5),
('Ford', 'Mustang', 'Iconic muscle car with custom trim.', '/images/ford-mustang.jpg', '/images/ford-mustang-tn.jpg', 58000, 9000, 2021, 5);

